# this cannot import from anything!!!

from exceptions import TCPDoneReceiving


def debugp(string):
    """
    A print i use for debugging so i know where to delete it afterwards.
    :param string:
    :return:
    """
    print(f"DEBUG: {string}")


# key modifiers:
CAPS_MODIFIER = 8
ALT_MODIFIER = 4
CTRL_MODIFIER = 2
SHIFT_MODIFIER = 1
NO_MODIFIER = 0
# you can `|` them together to get the different combinations.

EXPLOSION_ANIMATION = "misc/explosion.png"
ANIMATION_FRAME_RATE = 0.1
ANIMATION_X_COUNT, ANIMATION_Y_COUNT = 5, 3

OPAQUE = 35
A_LITTLE_OPAQUE = 100
NOT_OPAQUE = 255

WINDOW_NAME = "New Window"
WINDOW_WIDTH = 1275
WINDOW_HEIGHT = 600
INITIAL_WINDOW_LOCATION = 4, 50

IMAGES_SIZE = 16
SPRITE_SCALE_FACTOR = 3
VIEWING_OBJECT_SCALE_FACTOR = 5
PROCESS_IMAGE_SCALE_FACTOR = 1.3
INTERFACE_DISTANCE_FROM_COMPUTER = IMAGES_SIZE * SPRITE_SCALE_FACTOR - 20

DEFAULT_TEXT_Y_PADDING = -30
BUTTON_TEXT_PADDING = 8
SELECTED_OBJECT_PADDING = 5
DEFAULT_FONT = "Arial"
DEFAULT_FONT_SIZE = 10

FRAME_RATE = 1 / 60.0

DARK_GRAY = (20, 20, 20)
GRAY = (10, 10, 10)
LIGHT_COLOR_DIFF = 10
LIGHT_GRAY = (150, 150, 150)
VERY_LIGHT_GRAY = (180, 180, 180)
BLACK = (0, 0, 0)
WHITE = (255, 255, 255)
BLUE = (0, 0, 255)
LIGHT_BLUE = (100, 100, 255)
VERY_LIGHT_BLUE = (180, 180, 255)
PURPLE = (171, 71, 188)
BROWN = (62, 39, 35)
RED = (150, 0, 0)
YELLOW = (200, 200, 0)
GREEN = (0, 255, 0)
DARK_GREEN = (0, 100, 0)
PINK = (255, 170, 170)

SIDE_WINDOW_WIDTH = 230

DEFAULT_BUTTON_TEXT = "BuTTon"
DEFAULT_BUTTON_WIDTH = SIDE_WINDOW_WIDTH - 40
DEFAULT_BUTTON_HEIGHT = 35


def DEFAULT_BUTTON_LOCATION(button_index):
    return (WINDOW_WIDTH - SIDE_WINDOW_WIDTH + 20), (WINDOW_HEIGHT - 90 - (button_index * DEFAULT_BUTTON_HEIGHT))


WINDOW_BUTTONS_ID = -1
MAIN_BUTTONS_ID = 0

SIMULATION_MODE = 0  # the normal mode of the simulation
CONNECTING_MODE = 1  # The mode when we are connecting two computers (white on the edges)
VIEW_MODE = 2  # the mode when an object is pressed and we see it in the side window view
SNIFFING_MODE = 3  # the mode when we choose what computer will be sniffing
PINGING_MODE = 4  # the mode where we choose where a ping will be sent
DELETING_MODE = 5  # the mode where we choose what computer will be deleted

MODES_TO_COLORS = {
    SIMULATION_MODE: GRAY,
    CONNECTING_MODE: WHITE,
    VIEW_MODE: GRAY,
    SNIFFING_MODE: BLUE,
    PINGING_MODE: PURPLE,
    DELETING_MODE: BROWN,
}

CONNECTION_COLOR = WHITE
WIRELESS_CONNECTION_COLOR = LIGHT_GRAY
BLOCKED_CONNECTION_COLOR = RED
PL_CONNECTION_COLOR = DARK_GREEN
SELECTED_CONNECTION_COLOR = LIGHT_BLUE

VIEWING_IMAGE_COORDINATES = ((WINDOW_WIDTH - (SIDE_WINDOW_WIDTH / 2)) - (
            IMAGES_SIZE * VIEWING_OBJECT_SCALE_FACTOR / 2)), WINDOW_HEIGHT - (
                                        (IMAGES_SIZE * VIEWING_OBJECT_SCALE_FACTOR) + 15)
VIEWING_TEXT_COORDINATES = (WINDOW_WIDTH - (SIDE_WINDOW_WIDTH / 2)), VIEWING_IMAGE_COORDINATES[1] + 40

PIXELS_PER_SCROLL = 20

PAUSE_RECT_WIDTH = 10
PAUSE_RECT_HEIGHT = 60
PAUSE_RECT_COORDINATES = 20, ((WINDOW_HEIGHT - PAUSE_RECT_HEIGHT) - 10)

CIRCLE_SEGMENT_COUNT = 50
SINE_WAVE_MINIMAL_POINT_DISTANCE = 5
INITIAL_SINE_WAVE_ANGLE = 0
DEFAULT_SINE_WAVE_AMPLITUDE = 10
DEFAULT_SINE_WAVE_FREQUENCY = 10

DEFAULT_OUTLINE_WIDTH = 5

TEXTBOX_WIDTH = 400
TEXTBOX_HEIGHT = 170
TEXTBOX_COORDINATES = (WINDOW_WIDTH / 2) - (TEXTBOX_WIDTH / 2), (WINDOW_HEIGHT / 2) - (TEXTBOX_HEIGHT / 2)
TEXTBOX_UPPER_PART_HEIGHT = 30
TEXTBOX_COLOR = GRAY
TEXTBOX_OUTLINE_COLOR = LIGHT_BLUE
TEXTBOX_OUTLINE_WIDTH = DEFAULT_OUTLINE_WIDTH
POPUP_WINDOW_INFO_TEXT_PADDING = (TEXTBOX_WIDTH / 2), 6 * (TEXTBOX_HEIGHT / 7)
POPUP_WINDOW_TITLE_TEXT_PADDING = 35, TEXTBOX_HEIGHT + 22

SUBMIT_BUTTON_WIDTH = 100
SUBMIT_BUTTON_PADDING = (TEXTBOX_WIDTH / 2) - (SUBMIT_BUTTON_WIDTH / 2), 8
SUBMIT_BUTTON_COORDINATES = tuple(map(sum, zip(TEXTBOX_COORDINATES, SUBMIT_BUTTON_PADDING)))

NEW_WINDOW_LOCATION_PADDING = 10, -10

DEVICE_CREATION_BUTTON_SIZE = 80
DEVICE_CREATION_BUTTON_GAP = 5
